version: '3.3'
services:
  frontend:
    image: frontend-app:latest
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "frontend-app"
    ports:
      - '8080:30'